name: Build and Publish Docker Image

on:
  pull_request:
    types: [closed]
    branches:
      - dev
      - qa
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create production.env file
        run: echo "${{ secrets.PRODUCTION_ENV }}" > ./back/env/production.env

      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/radiobartinc/radiobart-back/my-app:${{ github.ref_name }} ./back

      - name: Test the Docker image
        run: |
          docker run -d --name test-container ghcr.io/radiobartinc/radiobart-back/my-app:${{ github.ref_name }}
          sleep 10
          docker ps -a
          docker logs test-container
          docker rm -f test-container

      - name: Push the Docker image
        run: |
          docker push ghcr.io/radiobartinc/radiobart-back/my-app:${{ github.ref_name }}

      - name: Clean up unused Docker images
        run: |
          docker image prune -f